# -*- coding: utf-8 -*-
"""Decision Tree Task 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R79CB90k6JBEJ0v5sA1vv0pSsBrlSiLe
"""

# Decision Tree Classifier for Customer Purchase Prediction

# Import Required Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt

# -----------------------------
# STEP 1: Load Dataset
# -----------------------------

# Replace with your file name if needed
data = pd.read_excel("/content/bank_marketing dataset.xlsx")

# Display first 5 rows
print("Dataset Preview:")
print(data.head())

# -----------------------------
# STEP 2: Data Preprocessing
# -----------------------------

# Encode categorical columns
label_encoders = {}

categorical_columns = [
    'Job',
    'Marital_Status',
    'Education',
    'Housing_Loan',
    'Personal_Loan',
    'Purchased'
]

for col in categorical_columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    label_encoders[col] = le

# -----------------------------
# STEP 3: Features and Target
# -----------------------------

X = data.drop(['Customer_ID', 'Purchased'], axis=1)
y = data['Purchased']

# -----------------------------
# STEP 4: Train-Test Split
# -----------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# -----------------------------
# STEP 5: Build Decision Tree Model
# -----------------------------

model = DecisionTreeClassifier(
    criterion='entropy',
    max_depth=5,
    random_state=42
)

# Train the model
model.fit(X_train, y_train)

# -----------------------------
# STEP 6: Predictions
# -----------------------------

y_pred = model.predict(X_test)

# -----------------------------
# STEP 7: Model Evaluation
# -----------------------------

accuracy = accuracy_score(y_test, y_pred)

print("\nAccuracy Score:")
print(accuracy)

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix

# Create confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Display confusion matrix
disp = ConfusionMatrixDisplay(confusion_matrix=cm)

disp.plot(cmap='Blues')

plt.title("Confusion Matrix")
plt.show()

